Upgrade to requests 2.5.3
Recent requests were leaking this exception from its vendored copy
of urllib3:

  ProtocolError: ('Connection aborted.', error(101, 'Network is unreachable'))

Update to a version where this is fixed so that we can correctly
detect that and switch to offline mode.

Change-Id: I28a223c0c4a4dd1f9c073e0ddf07985ff52386b2