Fix rendering error in change screen
This corrects the following error:
  urwid.listbox.ListBoxError: Widget <Pile selectable box/flow widget>
  at position 2 within listbox calculated X rows but rendered Y!

This happened when related changes links were winder than the screen.
They were rendered as FixedButtons, but there is no reason for them
to be.  This changes them to regular urwid Buttons which are flow
widgets and will line-wrap if needed.

Change-Id: Ia91beaffadbb7a3e5341b11c49bb2d6d74df4782