Fix exception in change list when change owner has no name
If a change owner has no name configured, attempting to view the list
of changes causes gertty to fail with:

  urwid.util.TagMarkupException: Invalid markup element: None

Change-Id: Idc0d13f4dfce45e29618c4abda7d6a70fc091e98